# #####################
# Combine all datasets#
#######################
library(metafor)
library(plyr)
# library(TwoSampleMR)
# download google sheet
# install.packages('gsheet')
library(gsheet)
# ieugwasr::get_access_token()
# ao<-available_outcomes()
# ao$ncase[ao$trait == "Lung cancer"]

# which(meta.tab$cancer == "Gastric adenocarcinoma")
# dat<-format_meta_data()
dat<-format_meta_data()
# max(dat$control[dat$study.abbreviation=="UKB"])
dat1<-incidence_meta_data(dat=dat)
meta_reg_function(dat=dat1)
dat2<-survival_meta_data(dat=dat)
meta_reg_function(dat=dat2)
dat3<-age_meta_data(dat=dat)
meta_reg_function(dat=dat3)
dat4<-stemcell_meta_data(dat=dat)
meta_reg_function(dat=dat4)
# dat5<-format_meta_data_smk_infl()

dat5<-system_meta_data(dat=dat)

M<-create_correlation_matrix(study=dat5)
M<-M$matrix
dat5$study.abbreviation
dat5$se_decoupled<-decoupling(s=dat5$se,C=M)
plot(dat5$se_decoupled,dat5$se)

dat5<-dat5[!duplicated(dat5$study.abbreviation),]
table(dat5$system_num)

meta_reg_function(dat=dat5)


meta_reg_function<-function(dat=NULL){
	Weights<-1/dat$se^2
	# Mods<-"stem_cell_divisions"
	# Mods<-"survival_time"
	# Mods<-"median.age.diagnosis"
	# Mods<-"smoking"
	# Mods<-"incidence"
	Col<-which(names(dat) == unique(dat$Mods))	
	Model<-summary(rma.uni(yi=dat$b,sei=dat$se_decoupled,weights=Weights,mods=dat[,Col],intercept=TRUE,slab=dat$cancer,method="REML",weighted=TRUE))
	return(Model)
}

# restrict the dataset to studies without ";" in id.outcome. These are datasets that have been generated by meta analysis of different studies of the same cancer within the FAMRC. It is easier to work out sample overlap by excluding these datasets. 
format_meta_data2<-function(){
	url<-"https://docs.google.com/spreadsheets/d/1sTliqObb08y3rdfB-vsYecjveud1pPk4FTWSYcpx3Xk/edit?usp=drive_open&ouid=103571138679663288585"
	meta.tab<-data.frame(gsheet2tbl(url))
	cols_keep_meta.tab1<-c("cancer","smoking","incidence","survival_time","name_in_seer","median.age.diagnosis","Cumulativ.e.number.of.divisions.of.all.stem.cells.per.lifetime..lscd.","name_in_Tomasetti_Vogelstein","study.abbreviation","study","site","system","cell","Cancer.Group","cases","controls","population","ID")
	load("~/fatty-acids/mr/results/mr_results_rep_v2.Rdata")
	load("~/MR_FattyAcids/data/summary_data/meta_data.Rdata")
	meta.tab<-meta.tab[,cols_keep_meta.tab1]
	meta.tab<-meta.tab[meta.tab$population=="European",]
	
	dat<-mr_res1
	dat<-dat[dat$population == "European" & dat$exposure == "AA:DGLA", ]
	dat<-dat[!duplicated(dat$id.outcome),]
	cols_keep_dat<-c("id.outcome","b","se","pval","exposure","nstudies","Q.p")
	dat1<-merge(dat[,cols_keep_dat],meta.tab,by.x="id.outcome",by.y="ID",all.x=FALSE)
	dat2<-dat[grep(";",dat$id.outcome),]
	dat2$outcome[!dat2$outcome  %in% meta.tab$cancer]<-"Overall cancer"
	cols_keep_meta.tab2<-c("cancer","incidence","survival_time","name_in_seer","median.age.diagnosis","Cumulativ.e.number.of.divisions.of.all.stem.cells.per.lifetime..lscd.","name_in_Tomasetti_Vogelstein")
	dat2<-merge(dat2[,c("outcome","population","cases","controls",cols_keep_dat)],unique(meta.tab[,	cols_keep_meta.tab2]),by.x="outcome",by.y="cancer")
	dat2$cancer <- dat2$outcome
	dat3<-rbind.fill(dat1,dat2)
	dat3$b<-as.numeric(dat3$b)
	dat3$se<-as.numeric(dat3$se)
	dat3$cases<-as.numeric(dat3$cases)
	dat3$controls<-as.numeric(dat3$controls)
	dat3<-dat3[dat3$id.outcome != 1499,]
	dat3<-dat3[dat3$id.outcome != 138,] #138 overlaps with meta analysis of 138; 165; 35 (cns and eye cancer)
	dat3<-dat3[dat3$id.outcome != 165,] #165 overlaps with meta analysis of 138; 165; 35 (cancer and eye cancer)
	cancers<-unique(dat3$cancer[is.na(dat3$system)])
	temp<-unique(dat3[which(dat3$cancer %in% cancers),c("system","cancer")])
	temp <- temp[!is.na(temp$system),]
	dat1<-dat3[is.na(dat3$system),]
	dat1<-dat1[,names(dat1) != "system" ]
	dat2<-dat3[!is.na(dat3$system),]
	dat1<-merge(dat1,temp,by="cancer")
	dat3<-rbind(dat1,dat2)
	dat3<-dat3[grep(";",dat3$id.outcome,invert=TRUE),]
	dat3<-dat3[order(dat3$cases,decreasing=TRUE),]
	dat3<-dat3[!duplicated(dat3$cancer),]
	return(dat3)
}


format_meta_data<-function(){
	url<-"https://docs.google.com/spreadsheets/d/1sTliqObb08y3rdfB-vsYecjveud1pPk4FTWSYcpx3Xk/edit?usp=drive_open&ouid=103571138679663288585"
	meta.tab<-data.frame(gsheet2tbl(url))
	cols_keep_meta.tab1<-c("cancer","smoking","incidence","survival_time","name_in_seer","median.age.diagnosis","Cumulativ.e.number.of.divisions.of.all.stem.cells.per.lifetime..lscd.","name_in_Tomasetti_Vogelstein","study.abbreviation","study","site","system","cell","Cancer.Group","cases","controls","population","ID")
	load("~/fatty-acids/mr/results/mr_results_rep_v2.Rdata")
	load("~/MR_FattyAcids/data/summary_data/meta_data.Rdata")
	meta.tab<-meta.tab[,cols_keep_meta.tab1]
	meta.tab<-meta.tab[meta.tab$population=="European",]
	
	dat<-mr_res1
	dat<-dat[dat$population == "European" & dat$exposure == "AA:DGLA", ]
	dat<-dat[!duplicated(dat$id.outcome),]
	cols_keep_dat<-c("id.outcome","b","se","pval","exposure","nstudies","Q.p")
	dat1<-merge(dat[,cols_keep_dat],meta.tab,by.x="id.outcome",by.y="ID",all.x=FALSE)
	dat2<-dat[grep(";",dat$id.outcome),]
	dat2$outcome[!dat2$outcome  %in% meta.tab$cancer]<-"Overall cancer"
	cols_keep_meta.tab2<-c("cancer","incidence","survival_time","name_in_seer","median.age.diagnosis","Cumulativ.e.number.of.divisions.of.all.stem.cells.per.lifetime..lscd.","name_in_Tomasetti_Vogelstein")
	dat2<-merge(dat2[,c("outcome","population","cases","controls",cols_keep_dat)],unique(meta.tab[,	cols_keep_meta.tab2]),by.x="outcome",by.y="cancer")
	dat2$cancer <- dat2$outcome
	dat3<-rbind.fill(dat1,dat2)
	dat3$b<-as.numeric(dat3$b)
	dat3$se<-as.numeric(dat3$se)
	dat3$cases<-as.numeric(dat3$cases)
	dat3$controls<-as.numeric(dat3$controls)
	dat3<-dat3[dat3$id.outcome != 1499,]
	dat3<-dat3[dat3$id.outcome != 138,] #138 overlaps with meta analysis of 138; 165; 35 (cns and eye cancer)
	dat3<-dat3[dat3$id.outcome != 165,] #165 overlaps with meta analysis of 138; 165; 35 (cancer and eye cancer)
	cancers<-unique(dat3$cancer[is.na(dat3$system)])
	temp<-unique(dat3[which(dat3$cancer %in% cancers),c("system","cancer")])
	temp <- temp[!is.na(temp$system),]
	dat1<-dat3[is.na(dat3$system),]
	dat1<-dat1[,names(dat1) != "system" ]
	dat2<-dat3[!is.na(dat3$system),]
	dat1<-merge(dat1,temp,by="cancer")
	dat3<-rbind(dat1,dat2)
	dat3<-dat3[order(dat3$cases,decreasing=TRUE),]
	dat3<-dat3[!duplicated(dat3$cancer),]
	return(dat3)
}

format_meta_data_smk_infl<-function(){
	url<-"https://docs.google.com/spreadsheets/d/1sTliqObb08y3rdfB-vsYecjveud1pPk4FTWSYcpx3Xk/edit?usp=drive_open&ouid=103571138679663288585"
	meta.tab<-data.frame(gsheet2tbl(url))
	cols_keep_meta.tab1<-c("cancer","smoking","incidence","survival_time","name_in_seer","median.age.diagnosis","Cumulativ.e.number.of.divisions.of.all.stem.cells.per.lifetime..lscd.","name_in_Tomasetti_Vogelstein","study.abbreviation","study","site","system","cell","Cancer.Group","cases","controls","population","ID")
	load("~/fatty-acids/mr/results/mr_results_rep_v2.Rdata")
	load("~/MR_FattyAcids/data/summary_data/meta_data.Rdata")
	meta.tab<-meta.tab[,cols_keep_meta.tab1]

	# meta.tab<-meta.tab[meta.tab$population=="European",]
	dat<-mr_res1
	dat1<-dat[dat$population == "European" & dat$exposure == "AA:DGLA", ]
	dat2<-dat[dat$population == "East Asian" & dat$exposure == "GLA:LA", ]
	dat<-rbind(dat1,dat2)

	# dat3<-dat[grep(";",dat$population),]
	dat<-dat[!duplicated(dat$id.outcome),]
	cols_keep_dat<-c("id.outcome","b","se","pval","exposure","nstudies","Q.p")
	dat1<-merge(dat[,cols_keep_dat],meta.tab,by.x="id.outcome",by.y="ID",all.x=FALSE)
	dat2<-dat[grep(";",dat$id.outcome),]
	head(dat2)
	dat2$outcome[!dat2$outcome  %in% meta.tab$cancer]<-"Overall cancer"
	dat2$outcome == "Bladder cancer"
	cols_keep_meta.tab2<-c("cancer","smoking","incidence","survival_time","name_in_seer","median.age.diagnosis","Cumulativ.e.number.of.divisions.of.all.stem.cells.per.lifetime..lscd.","name_in_Tomasetti_Vogelstein")
	dat2<-merge(dat2[,c("outcome","population","cases","controls",cols_keep_dat)],unique(meta.tab[,	cols_keep_meta.tab2]),by.x="outcome",by.y="cancer")
	dat2$cancer <- dat2$outcome
	dat3<-rbind.fill(dat1,dat2)
	dat3$b<-as.numeric(dat3$b)
	dat3$se<-as.numeric(dat3$se)
	dat3$cases<-as.numeric(dat3$cases)
	dat3$controls<-as.numeric(dat3$controls)
	dat3<-dat3[dat3$id.outcome != 1499,]
	
	# dat3$study[grep(";",dat3$id.outcome),]
	dat3<-dat3[order(dat3$cases,decreasing=TRUE),]
	a<-dat3[grep(";",dat3$id.outcome),]
	b<-dat3[grep(";",dat3$id.outcome,invert=TRUE),]
	ids<-trimws(unlist(strsplit(a$id,split=";")))
	# remove results overlapping on id.outcome
	b<-b[!b$id.outcome %in% ids,]
	b1<-b[b$study %in% c("UK Biobank","FinnGen","Biobank Japan"),]
	b2<-b[!b$study %in% c("UK Biobank","FinnGen","Biobank Japan","InterLymph"),]
	# remove tumour subtypes from cancer consortia 
	b2<-b2[!duplicated(b2$study),]
	b<-rbind(b1,b2)
	c<-rbind(a,b)
	c<-c[!duplicated(c$cancer),]
	c$smoking[is.na(c$smoking)]<-0	

	# remove results with overlapping studies


	return(c)
}


system_meta_data<-function(dat=NULL){	
	dat<-dat[!is.na(dat$system),]	
	dat<-dat[order(dat$cases,decreasing=TRUE),]
	dat<-dat[!duplicated(dat$cancer),]		
	
	dat$system[dat$Cancer.Group %in% "Mouth & throat cancer"]<-"digestive"
	dat$system[dat$cancer=="Oral cavity and pharyngeal cancer" ]<-"digestive"
	dat$system_numeric<-dat$system
	dat$system_numeric[dat$system_numeric != "digestive"]<-"0"
	dat$system_numeric[dat$system_numeric == "digestive"]<-"1"
	dat$system_numeric<-as.numeric(dat$system_numeric)
	dat$Mods<-"system_numeric"
	return(dat)
}  



incidence_meta_data<-function(dat=NULL){	
	dat_inc<-dat[!is.na(dat$incidence),]	
	dat_inc<-dat_inc[order(dat_inc$cases,decreasing=TRUE),]
	dat_inc<-dat_inc[!duplicated(dat_inc$cancer),]		
	dat_inc$Mods<-"incidence"
	return(dat_inc)
}

survival_meta_data<-function(dat=NULL){	
	dat1<-dat[!is.na(dat$survival_time),]	
	dat1<-dat1[order(dat1$cases,decreasing=TRUE),]
	dat1<-dat1[!duplicated(dat1$cancer),]
	dat1$Mods<-"survival_time"
	return(dat1)
}

age_meta_data<-function(dat=NULL){
	dat1<-dat[!is.na(dat$median.age.diagnosis),]	
	dat1<-dat1[order(dat1$cases,decreasing=TRUE),]
	dat1<-dat1[!duplicated(dat1$cancer),]
	dat1$Mods<-"median.age.diagnosis"
	return(dat1)

}

stemcell_meta_data<-function(dat=NULL){
	dat1<-dat[!is.na(dat$Cumulativ.e.number.of.divisions.of.all.stem.cells.per.lifetime..lscd.),]	
	names(dat1)[names(dat1)=="Cumulativ.e.number.of.divisions.of.all.stem.cells.per.lifetime..lscd."]<-"stem_cell_divisions"
	dat1<-dat1[order(dat1$cases,decreasing=TRUE),]
	dat1<-dat1[!duplicated(dat1$cancer),]	
	dat1$Mods<-"stem_cell_divisions"
	return(dat1)

}

# mr_res1[mr_res1$id.outcome=="76",]
# dat<-format_meta_data2()

# smoking_meta_dat<-function(dat=NULL){
# 	# bladder cancer, cervical cancer, colorectal cancer, esophageal cancer, kidney cancer, laryngeal cancer, acute myeloid leukemia, liver cancer, lung cancer, oral cavity and pharyngeal cancer, pancreatic cancer and stomach cancer. 

# 	# sort(unique(dat$cancer[which(dat$smoking==1)]))
# 	# sort(unique(dat$cancer[is.na(dat$smoking)]))
	
# 	dat<-dat[order(dat$cases,decreasing=TRUE),]
	
# 	return(dat)
# }
	# chronic inflammatory conditions + infectous agents
	# how infectious agents cancers matched to cancers in FAMRC
agents<-c("Biliary tract cancer",# Cholangiosarcoma, 
		"Colon cancer",# colon carcnoma, 
		"Gastric adenocarcinoma",# Gastric adenocarcinoma, 
		 "Liver cancer",# Hepatocellular carcinoma
		 "B cell non-hodgkin lymphoma",   # B-cell non-Hodgkin’s lymphoma,     
		 "Non-hodgkin lymphoma unspecified",# Non-Hodgkin’s lymphoma, 
		 "Ovarian cancer",     # Ovarian carcinoma, 
		 "Cervical cancer",   # cervical/anal carcinoma   
		 "Bladder cancer",# Bladder, 
		  "Rectal cancer") # rectal carcinoma, 

Infl_cancers<-c("Uveal melanoma","Diffuse large b cell lymphoma","Melanoma","Gastric adenocarcinoma","Pancreatic cancer", "Oral cavity and pharyngeal cancer" , "Lung cancer","Esophageal adenocarcinoma","Esophageal squamous cell carcinoma","Colorectal cancer",	"Bladder cancer","Pleural mesothelioma", "Marginal zone lymphoma","Malignant skin cancer")


# DECOUPLE the standard errors
# create correlation matrix for cancer results based on overlap in subjects 

head(dat5)

names(dat5)
id1<-dat$id.outcome[grep(";",dat$id.outcome)]
id1<-as.numeric(trimws(unlist(strsplit(id1,split=";"))))
id2<-dat$id.outcome[grep(";",dat$id.outcome,invert=TRUE)]
id2<-as.numeric(id2)
id<-c(id1,id2)
dups<-id[which(duplicated(id))]



dat[grep(1,dat$id.outcome),]
dat$cancer[dat$id.outcome ==  "1; 135; 70"]
dat$cancer[dat$id.outcome ==  "1"]

dat[grep(165,dat$id.outcome),]

dat<-format_meta_data2()
dim(dat)

# assume 50% overlap when from same consortium?
dat$IDS<-paste(dat$study.abbreviation,dat$Cancer.Group)

dat[order(dat$study.abbreviation,dat$Cancer.Group),c("cancer","study.abbreviation","site","Cancer.Group")]
N1<-dat$cases[1]+dat$controls[1]
N2<-dat$cases[2]+dat$controls[2]

correlation_between_cancers(N1=N1,N2=N2,k=0)

# what is unit of analysis?
# 1. one result per cancer site 
	# where there are duplicates, retain the duplicate with largest sample size
	# disadvantage: lose tumour subtypes e.g. skin cancer rather than melanoma, basal or sqaumous. Analysis will be based on malignant skin cancer in UKB
	# disadvantage: unclear what is cancer site for blood cancers. just overall risk of blood cancer in UKB? 

# 2. one result per subtype per site?
	# exclude overall groupings like breast, lung, ovarian and prostate
	# retain skin cancer and blood cancer subtypes 
	# disadvantage is increases overlap in participats substantially 

# 3. one result per Cancer_Group?
	# this is similar to one result per cancer site but differentiates between lymphoid leukemia and non hodkins lymphoma in InterLymph 


# sensitivity analyses on 1 and 2
# model overlap in participants 
# assume 25% overlap all cancers? 
# assume 100% overlap in controls and 0% overal for cases for cancers from same study/consortium?
# for one result per subtype, may be overlap in cases for blood cancer subtypes and ovarian subtypes? 


unique(dat[order(dat$site),c("site","Cancer.Group")])
studies<-unique(dat$study.abbreviation)

study<-dat[dat$study.abbreviation=="UKB",]
study[,c("cancer","cases","controls","Cancer.Group")]
# correlation_between_cancers()
# lapply(studies,FUN=function(x)
	# nrow(dat[dat$study.abbreviation==x,])^2)

40^2
M<-rep(0,nrow(mr_res)^2)
M<-matrix(M,nrow=nrow(mr_res),ncol=nrow(mr_res))



corr_results_list2[1]

[2]
,2]
,2]
M[2,1]




corr_results_list2
length(corr_results_list2)
length(corr_results)

length(corr_results)

test<-study[6:8,]
test<-study[c(12,20),]
test<-study[c(22,24),]

source("~/fatty-acids/mr/scripts/mr_functions.R")
source("~/fatty-acids/mr/scripts/mr_plot_functions.R")


mr_res<-format_metareg(prune_blood_cancers=FALSE,drop_skin_cancers=FALSE)

url<-"https://docs.google.com/spreadsheets/d/1sTliqObb08y3rdfB-vsYecjveud1pPk4FTWSYcpx3Xk/edit?usp=drive_open&ouid=103571138679663288585"
meta.tab<-data.frame(gsheet2tbl(url))

mr_res[order(mr_res$site),c("cancer","Cancer.Group","site","study.abbreviation.y","cases","controls")]
names(mr_res)

test<-mr_res[c(14,15),]
mr_res$study.abbreviation
dim(mr_res)

unique(dat$study.abbreviation)

max(as.numeric(meta.tab$control[meta.tab$study.abbreviation=="InterLymph"]),na.rm=TRUE)
unique(meta.tab$cancer)

